license_id: cc-by
methodology: Other
methodology_other: Please refer to [EADW-CDI-Factsheet](https://droughtwatch.icpac.net/documents/3/EADW-CDI-Factsheet.pdf)
dataset_source: ICPAC
package_creator: HDX Data Systems Team
private: False
maintainer: aa13de36-28c5-47a7-8d0b-6d7c754ba8c8
owner_org:  04436cdf-24da-4826-b5b8-67cba9962423
